---
name: Cache

on:
  workflow_call:
    inputs:
      cache:
        description: Cachix cache to populate
        required: true
        type: string
      flake:
        description: Target flake on which to run `nix flake check`
        required: false
        type: string
        default: ./nix
    secrets:
      cachix-auth-token:
        description: Cachix authorization token with write access

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache:
    name: Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - run: |
          : nix flake check
          nix flake check ${{ inputs.flake }} --keep-going --print-build-logs

      - run: |
          : install cachix
          nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install

      - run: |
          nix build --json \
            | jq --raw-output '.[].outputs | to_entries[].value' \
            | cachix push ${{ inputs.cache }}
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.cachix-auth-token }}
