---
name: CI

on:
  workflow_call:
    inputs:
      flake:
        description: Target flake on which to run `nix flake check`
        required: false
        type: string
        default: ./nix

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - run: |
          : nix flake check
          nix flake check ${{ inputs.flake }} --keep-going --print-build-logs
